/* This file was generated by the Hex-Rays decompiler version 7.7.0.220118.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

NTSTATUS sub_11008(NTSTRSAFE_PWSTR pszDest, unsigned __int64 a2, const wchar_t *a3, ...);
void sub_11060();
__int64 __fastcall sub_1108C(__int64 a1, IRP *a2);
__int64 __fastcall sub_112F4(__int64 a1, IRP *a2);
__int64 __fastcall sub_11360(__int64 a1, __int64 a2, struct _KEVENT *a3);
__int64 __fastcall sub_11400(__int64 a1, IRP *a2);
__int64 __fastcall sub_11538(__int64 a1, IRP *a2);
__int64 __fastcall sub_11560(__int64 a1, IRP *a2);
__int64 __fastcall sub_116C4(__int64 a1, IRP *a2);
__int64 __fastcall sub_11828(PDRIVER_OBJECT DriverObject); // idb
void __fastcall sub_11950(uintptr_t a1);
// void __cdecl __noreturn _report_gsfailure(uintptr_t StackCookie);
// ULONG DbgPrint(PCSTR Format, ...);
// NTSTATUS __stdcall RtlStringVPrintfWorkerW(NTSTRSAFE_PWSTR pszDest, size_t cchDest, size_t *pcchNewDestLength, NTSTRSAFE_PCWSTR pszFormat, va_list argList);
// NTSTATUS __stdcall RtlStringLengthWorkerW(STRSAFE_PCNZWCH psz, size_t cchMax, size_t *pcchLength);
NTSTATUS __fastcall sub_11A70(const wchar_t *a1, size_t a2, size_t *a3, size_t a4);
// int __cdecl vsnwprintf_l(wchar_t *DstBuf, size_t MaxCount, const wchar_t *Format, _locale_t Locale, va_list ArgList);
// int __cdecl vsnwprintf(wchar_t *Dest, size_t Count, const wchar_t *Format, va_list Args);
// void *__cdecl memset(void *Dst, int Val, size_t Size);
// int __cdecl flsbuf(int Ch, FILE *File);
// ULONG invalid_parameter();
// void __fastcall write_char(wchar_t a1, __int64 a2, _DWORD *a3);
// void __fastcall write_multi_char(wchar_t a1, int a2, __int64 a3, _DWORD *a4);
// void __fastcall write_string(wchar_t *a1, int a2, __int64 a3, _DWORD *a4);
// __int64 __fastcall woutput_l(__int64 a1, wchar_t *a2, __int64 a3, int *a4);
// void __fastcall _GSHandlerCheckCommon(unsigned __int64 a1, __int64 a2, __int64 a3);
// __int64 __fastcall _GSHandlerCheck(__int64 a1, unsigned __int64 a2, __int64 a3, __int64 a4);
// int __cdecl get_printf_count_output();
// wint_t __cdecl fputwc_nolock(wchar_t Ch, FILE *File);
// int __cdecl mbtowc(wchar_t *DstCh, const char *SrcCh, size_t SrcSizeInBytes);
// __int64 __fastcall flswbuf(__int64 a1, __int64 a2);
// WCHAR __stdcall RtlAnsiCharToUnicodeChar(PUCHAR *SourceCharacter);
// void *__cdecl memmove(void *Dst, const void *Src, size_t MaxCount);
NTSTATUS __stdcall DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath);

//-------------------------------------------------------------------------
// Data declarations

// extern PVOID (__stdcall *ExAllocatePoolWithTag)(POOL_TYPE PoolType, SIZE_T NumberOfBytes, ULONG Tag);
// extern PDEVICE_OBJECT (__stdcall *IoGetLowerDeviceObject)(PDEVICE_OBJECT DeviceObject);
// extern PIRP (__stdcall *IoBuildDeviceIoControlRequest)(ULONG IoControlCode, PDEVICE_OBJECT DeviceObject, PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, BOOLEAN InternalDeviceIoControl, PKEVENT Event, PIO_STATUS_BLOCK IoStatusBlock);
// extern NTSTATUS (__stdcall *IoDeleteSymbolicLink)(PUNICODE_STRING SymbolicLinkName);
// extern void (__stdcall *ExFreePoolWithTag)(PVOID P, ULONG Tag);
// extern void (__stdcall *RtlInitUnicodeString)(PUNICODE_STRING DestinationString, PCWSTR SourceString);
// extern void (__stdcall *IoDeleteDevice)(PDEVICE_OBJECT DeviceObject);
// extern LONG (__stdcall *KeSetEvent)(PRKEVENT Event, KPRIORITY Increment, BOOLEAN Wait);
// extern void (__stdcall *KeInitializeEvent)(PRKEVENT Event, EVENT_TYPE Type, BOOLEAN State);
// extern void (__stdcall *IoFreeMdl)(PMDL Mdl);
// extern PVOID (__stdcall *MmMapLockedPagesSpecifyCache)(PMDL MemoryDescriptorList, KPROCESSOR_MODE AccessMode, MEMORY_CACHING_TYPE CacheType, PVOID RequestedAddress, ULONG BugCheckOnFailure, ULONG Priority);
// extern NTSTATUS (__stdcall *IoGetDeviceObjectPointer)(PUNICODE_STRING ObjectName, ACCESS_MASK DesiredAccess, PFILE_OBJECT *FileObject, PDEVICE_OBJECT *DeviceObject);
// extern PIRP (__stdcall *IoBuildAsynchronousFsdRequest)(ULONG MajorFunction, PDEVICE_OBJECT DeviceObject, PVOID Buffer, ULONG Length, PLARGE_INTEGER StartingOffset, PIO_STATUS_BLOCK IoStatusBlock);
// extern void (__stdcall *IofCompleteRequest)(PIRP Irp, CCHAR PriorityBoost);
// extern NTSTATUS (__stdcall *KeWaitForSingleObject)(PVOID Object, KWAIT_REASON WaitReason, KPROCESSOR_MODE WaitMode, BOOLEAN Alertable, PLARGE_INTEGER Timeout);
// extern void (__stdcall *IoFreeIrp)(PIRP Irp);
// extern PDEVICE_OBJECT (__stdcall *IoGetAttachedDeviceReference)(PDEVICE_OBJECT DeviceObject);
// extern LONG (__stdcall *RtlCompareUnicodeString)(PCUNICODE_STRING String1, PCUNICODE_STRING String2, BOOLEAN CaseInSensitive);
// extern void (__stdcall *MmUnlockPages)(PMDL MemoryDescriptorList);
// extern LONG_PTR (__stdcall *ObfReferenceObject)(PVOID Object);
// extern NTSTATUS (__stdcall *IoCreateSymbolicLink)(PUNICODE_STRING SymbolicLinkName, PUNICODE_STRING DeviceName);
// extern LONG_PTR (__stdcall *ObfDereferenceObject)(PVOID Object);
// extern NTSTATUS (__stdcall *RtlUnicodeStringToInteger)(PCUNICODE_STRING String, ULONG Base, PULONG Value);
// extern NTSTATUS (__stdcall *IoCreateDevice)(PDRIVER_OBJECT DriverObject, ULONG DeviceExtensionSize, PUNICODE_STRING DeviceName, ULONG DeviceType, ULONG DeviceCharacteristics, BOOLEAN Exclusive, PDEVICE_OBJECT *DeviceObject);
// extern void (__stdcall *ObDereferenceObjectDeferDelete)(PVOID Object);
// extern NTSTATUS (__stdcall *IofCallDriver)(PDEVICE_OBJECT DeviceObject, PIRP Irp);
ULONG_PTR BugCheckParameter2 = 47936899621426ui64; // idb
ULONG_PTR BugCheckParameter3 = 18446696136809930189ui64; // idb
struct _UNICODE_STRING DeviceName = { 0u, 0u, NULL }; // idb
struct _UNICODE_STRING SymbolicLinkName = { 0u, 0u, NULL }; // idb
PDEVICE_OBJECT DeviceObject = NULL; // idb


//----- (0000000000011008) ----------------------------------------------------
NTSTATUS sub_11008(NTSTRSAFE_PWSTR pszDest, unsigned __int64 a2, const wchar_t *a3, ...)
{
  size_t v3; // rbx
  NTSTATUS result; // eax
  va_list va; // [rsp+68h] [rbp+20h] BYREF

  va_start(va, a3);
  v3 = a2 >> 1;
  result = sub_11A70(pszDest, a2 >> 1, 0i64, 0x7FFFFFFFi64);
  if ( result >= 0 )
    return RtlStringVPrintfWorkerW(pszDest, v3, 0i64, a3, va);
  return result;
}
// 11A70: using guessed type __int64 __fastcall sub_11A70(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000011060) ----------------------------------------------------
void sub_11060()
{
  IoDeleteSymbolicLink(&SymbolicLinkName);
  IoDeleteDevice(DeviceObject);
}

//----- (000000000001108C) ----------------------------------------------------
__int64 __fastcall sub_1108C(__int64 a1, IRP *a2)
{
  struct _IO_STACK_LOCATION *CurrentStackLocation; // rsi
  unsigned int v4; // ebx
  PFILE_OBJECT v5; // rsi
  struct _DEVICE_OBJECT *v6; // rdi
  bool v7; // zf
  PDEVICE_OBJECT AttachedDeviceReference; // r12
  PDEVICE_OBJECT LowerDeviceObject; // rdi
  struct _DRIVER_OBJECT *DriverObject; // rcx
  int v12; // [rsp+20h] [rbp-F8h]
  ULONG Value; // [rsp+30h] [rbp-E8h] BYREF
  UNICODE_STRING String; // [rsp+38h] [rbp-E0h] BYREF
  PDEVICE_OBJECT DeviceObject; // [rsp+48h] [rbp-D0h] BYREF
  PFILE_OBJECT FileObject; // [rsp+50h] [rbp-C8h] BYREF
  struct _UNICODE_STRING DestinationString; // [rsp+58h] [rbp-C0h] BYREF
  WCHAR SourceString[64]; // [rsp+70h] [rbp-A8h] BYREF

  CurrentStackLocation = a2->Tail.Overlay.CurrentStackLocation;
  Value = 0;
  String.Buffer = 0i64;
  if ( CurrentStackLocation && (v5 = CurrentStackLocation->FileObject) != 0i64 && v5->FileName.Length > 1u )
  {
    String.Buffer = (PWSTR)ExAllocatePoolWithTag(NonPagedPool, v5->FileName.Length, 0x72647365u);
    if ( String.Buffer )
    {
      String.Length = v5->FileName.Length - 2;
      String.MaximumLength = v5->FileName.Length;
      memmove(String.Buffer, v5->FileName.Buffer + 1, v5->FileName.Length - 2i64);
      v4 = RtlUnicodeStringToInteger(&String, 0xAu, &Value);
      if ( !v4 )
      {
        if ( Value >= 0x64 )
          goto LABEL_21;
        DeviceObject = 0i64;
        FileObject = 0i64;
        memset(SourceString, 0, 120);
        if ( sub_11008(SourceString, v4 + 120, L"\\Device\\Harddisk%u\\Partition0", Value, v4 & v12) )
          goto LABEL_21;
        RtlInitUnicodeString(&DestinationString, SourceString);
        if ( IoGetDeviceObjectPointer(&DestinationString, 0, &FileObject, &DeviceObject) )
          goto LABEL_21;
        ObfReferenceObject(DeviceObject);
        v6 = DeviceObject;
        v7 = DeviceObject == 0i64;
        v5->FsContext = FileObject;
        if ( v7 )
          goto LABEL_21;
        AttachedDeviceReference = IoGetAttachedDeviceReference(v6);
        if ( !AttachedDeviceReference )
          goto LABEL_21;
        ObfDereferenceObject(v6);
        RtlInitUnicodeString(&DestinationString, L"Disk");
        LowerDeviceObject = AttachedDeviceReference;
        do
        {
          DriverObject = LowerDeviceObject->DriverObject;
          if ( DriverObject )
          {
            if ( !RtlCompareUnicodeString(&DriverObject->DriverExtension->ServiceKeyName, &DestinationString, 1u) )
              break;
            if ( AttachedDeviceReference != LowerDeviceObject )
              ObfDereferenceObject(LowerDeviceObject);
          }
          LowerDeviceObject = IoGetLowerDeviceObject(LowerDeviceObject);
        }
        while ( LowerDeviceObject );
        if ( !LowerDeviceObject )
        {
LABEL_21:
          v4 = -1073741811;
        }
        else
        {
          ObfDereferenceObject(AttachedDeviceReference);
          v5->FsContext2 = LowerDeviceObject;
          a2->IoStatus.Information = 0i64;
        }
      }
    }
    else
    {
      v4 = -1073741670;
    }
    if ( String.Buffer )
    {
      ExFreePoolWithTag(String.Buffer, 0);
      String.Buffer = 0i64;
      String.Length = 0;
      String.MaximumLength = 0;
    }
  }
  else
  {
    v4 = -1073741811;
  }
  a2->IoStatus.Status = v4;
  IofCompleteRequest(a2, 0);
  return v4;
}
// 1118E: variable 'v12' is possibly undefined
// 12B10: using guessed type wchar_t aDeviceHarddisk[30];

//----- (00000000000112F4) ----------------------------------------------------
__int64 __fastcall sub_112F4(__int64 a1, IRP *a2)
{
  struct _IO_STACK_LOCATION *CurrentStackLocation; // rdx
  PFILE_OBJECT FileObject; // rax
  PVOID FsContext2; // rcx
  PVOID FsContext; // rdi

  CurrentStackLocation = a2->Tail.Overlay.CurrentStackLocation;
  if ( CurrentStackLocation )
  {
    FileObject = CurrentStackLocation->FileObject;
    if ( FileObject )
    {
      FsContext2 = FileObject->FsContext2;
      if ( FsContext2 )
      {
        FsContext = FileObject->FsContext;
        ObfDereferenceObject(FsContext2);
        if ( FsContext )
          ObfDereferenceObject(FsContext);
      }
    }
  }
  a2->IoStatus.Information = 0i64;
  a2->IoStatus.Status = 0;
  IofCompleteRequest(a2, 0);
  return 0i64;
}

//----- (0000000000011360) ----------------------------------------------------
__int64 __fastcall sub_11360(__int64 a1, __int64 a2, struct _KEVENT *a3)
{
  void *v3; // rcx
  struct _MDL *v6; // rbx

  v3 = *(void **)(a2 + 24);
  if ( v3 && (*(_BYTE *)(a2 + 16) & 0x20) != 0 )
    ExFreePoolWithTag(v3, 0);
  while ( *(_QWORD *)(a2 + 8) )
  {
    v6 = *(struct _MDL **)(a2 + 8);
    *(_QWORD *)(a2 + 8) = v6->Next;
    MmUnlockPages(v6);
    IoFreeMdl(v6);
  }
  if ( *(_BYTE *)(a2 + 65) && a3 )
  {
    *(__m128i *)*(_QWORD *)(a2 + 72) = _mm_loadu_si128((const __m128i *)(a2 + 48));
    KeSetEvent(a3, 1, 0);
  }
  IoFreeIrp((PIRP)a2);
  return 3221225494i64;
}

//----- (0000000000011400) ----------------------------------------------------
__int64 __fastcall sub_11400(__int64 a1, IRP *a2)
{
  struct _IO_STACK_LOCATION *CurrentStackLocation; // rbx
  PFILE_OBJECT FileObject; // rax
  struct _DEVICE_OBJECT *FsContext2; // rcx
  struct _DEVICE_OBJECT *AttachedDeviceReference; // rsi
  unsigned int Status; // ebx
  struct _IRP *OutputBuffer; // rbp
  IRP *v9; // rax
  struct _IO_STATUS_BLOCK IoStatusBlock; // [rsp+50h] [rbp-38h] BYREF
  struct _KEVENT Event; // [rsp+60h] [rbp-28h] BYREF

  CurrentStackLocation = a2->Tail.Overlay.CurrentStackLocation;
  if ( CurrentStackLocation
    && (FileObject = CurrentStackLocation->FileObject) != 0i64
    && (FsContext2 = (struct _DEVICE_OBJECT *)FileObject->FsContext2) != 0i64 )
  {
    AttachedDeviceReference = IoGetAttachedDeviceReference(FsContext2);
    if ( AttachedDeviceReference && (OutputBuffer = a2->AssociatedIrp.MasterIrp) != 0i64 )
    {
      KeInitializeEvent(&Event, NotificationEvent, 0);
      v9 = IoBuildDeviceIoControlRequest(
             CurrentStackLocation->Parameters.Read.ByteOffset.LowPart,
             AttachedDeviceReference,
             OutputBuffer,
             CurrentStackLocation->Parameters.Create.Options,
             OutputBuffer,
             CurrentStackLocation->Parameters.Read.Length,
             0,
             &Event,
             &IoStatusBlock);
      if ( v9 )
      {
        Status = IofCallDriver(AttachedDeviceReference, v9);
        if ( Status == 259 )
        {
          KeWaitForSingleObject(&Event, Executive, 0, 0, 0i64);
          Status = IoStatusBlock.Status;
        }
        a2->IoStatus.Information = IoStatusBlock.Information;
      }
      else
      {
        Status = -1073741670;
      }
    }
    else
    {
      Status = -1073741811;
    }
    if ( AttachedDeviceReference )
      ObDereferenceObjectDeferDelete(AttachedDeviceReference);
  }
  else
  {
    Status = -1073741811;
  }
  a2->IoStatus.Status = Status;
  IofCompleteRequest(a2, 0);
  return Status;
}

//----- (0000000000011538) ----------------------------------------------------
__int64 __fastcall sub_11538(__int64 a1, IRP *a2)
{
  a2->IoStatus.Status = 0;
  a2->IoStatus.Information = 0i64;
  IofCompleteRequest(a2, 0);
  return 0i64;
}

//----- (0000000000011560) ----------------------------------------------------
__int64 __fastcall sub_11560(__int64 a1, IRP *a2)
{
  union _LARGE_INTEGER *CurrentStackLocation; // rsi
  union _LARGE_INTEGER v4; // rax
  struct _DEVICE_OBJECT *v5; // rbx
  PMDL MdlAddress; // rcx
  PVOID MappedSystemVa; // r8
  unsigned int Status; // ebx
  PIRP v9; // rbp
  struct _IO_STACK_LOCATION *v10; // r11
  struct _IO_STATUS_BLOCK IoStatusBlock; // [rsp+30h] [rbp-38h] BYREF
  struct _KEVENT Event; // [rsp+40h] [rbp-28h] BYREF
  union _LARGE_INTEGER Timeout; // [rsp+78h] [rbp+10h] BYREF

  CurrentStackLocation = (union _LARGE_INTEGER *)a2->Tail.Overlay.CurrentStackLocation;
  if ( !CurrentStackLocation )
    goto LABEL_15;
  v4 = CurrentStackLocation[6];
  if ( !v4.QuadPart )
    goto LABEL_15;
  v5 = *(struct _DEVICE_OBJECT **)(v4.QuadPart + 32);
  if ( !v5 )
    goto LABEL_15;
  MdlAddress = a2->MdlAddress;
  if ( (MdlAddress->MdlFlags & 5) != 0 )
    MappedSystemVa = MdlAddress->MappedSystemVa;
  else
    MappedSystemVa = MmMapLockedPagesSpecifyCache(MdlAddress, 0, MmCached, 0i64, 0, 0x10u);
  if ( !MappedSystemVa )
    goto LABEL_8;
  Timeout = CurrentStackLocation[3];
  if ( Timeout.QuadPart < 0 )
  {
LABEL_15:
    Status = -1073741811;
    goto LABEL_16;
  }
  v9 = IoBuildAsynchronousFsdRequest(4u, v5, MappedSystemVa, CurrentStackLocation[1].LowPart, &Timeout, &IoStatusBlock);
  if ( !v9 )
  {
LABEL_8:
    Status = -1073741670;
    goto LABEL_16;
  }
  KeInitializeEvent(&Event, NotificationEvent, 0);
  v10 = v9->Tail.Overlay.CurrentStackLocation;
  v10[-1].CompletionRoutine = (PIO_COMPLETION_ROUTINE)sub_11360;
  v10[-1].Control = -32;
  v10[-1].Context = &Event;
  Status = IofCallDriver(v5, v9);
  if ( Status == 259 )
  {
    KeWaitForSingleObject(&Event, Executive, 0, 0, 0i64);
    Status = IoStatusBlock.Status;
  }
  if ( !Status )
    a2->IoStatus.Information = CurrentStackLocation[1].LowPart << 9;
LABEL_16:
  a2->IoStatus.Status = Status;
  IofCompleteRequest(a2, 0);
  return Status;
}

//----- (00000000000116C4) ----------------------------------------------------
__int64 __fastcall sub_116C4(__int64 a1, IRP *a2)
{
  union _LARGE_INTEGER *CurrentStackLocation; // rsi
  union _LARGE_INTEGER v4; // rax
  struct _DEVICE_OBJECT *v5; // rbx
  PMDL MdlAddress; // rcx
  PVOID MappedSystemVa; // r8
  unsigned int Status; // ebx
  PIRP v9; // rbp
  struct _IO_STACK_LOCATION *v10; // r11
  struct _IO_STATUS_BLOCK IoStatusBlock; // [rsp+30h] [rbp-38h] BYREF
  struct _KEVENT Event; // [rsp+40h] [rbp-28h] BYREF
  union _LARGE_INTEGER Timeout; // [rsp+78h] [rbp+10h] BYREF

  CurrentStackLocation = (union _LARGE_INTEGER *)a2->Tail.Overlay.CurrentStackLocation;
  if ( !CurrentStackLocation )
    goto LABEL_15;
  v4 = CurrentStackLocation[6];
  if ( !v4.QuadPart )
    goto LABEL_15;
  v5 = *(struct _DEVICE_OBJECT **)(v4.QuadPart + 32);
  if ( !v5 )
    goto LABEL_15;
  MdlAddress = a2->MdlAddress;
  if ( (MdlAddress->MdlFlags & 5) != 0 )
    MappedSystemVa = MdlAddress->MappedSystemVa;
  else
    MappedSystemVa = MmMapLockedPagesSpecifyCache(MdlAddress, 0, MmCached, 0i64, 0, 0x10u);
  if ( !MappedSystemVa )
    goto LABEL_8;
  Timeout = CurrentStackLocation[3];
  if ( Timeout.QuadPart < 0 )
  {
LABEL_15:
    Status = -1073741811;
    goto LABEL_16;
  }
  v9 = IoBuildAsynchronousFsdRequest(3u, v5, MappedSystemVa, CurrentStackLocation[1].LowPart, &Timeout, &IoStatusBlock);
  if ( !v9 )
  {
LABEL_8:
    Status = -1073741670;
    goto LABEL_16;
  }
  KeInitializeEvent(&Event, NotificationEvent, 0);
  v10 = v9->Tail.Overlay.CurrentStackLocation;
  v10[-1].CompletionRoutine = (PIO_COMPLETION_ROUTINE)sub_11360;
  v10[-1].Control = -32;
  v10[-1].Context = &Event;
  Status = IofCallDriver(v5, v9);
  if ( Status == 259 )
  {
    KeWaitForSingleObject(&Event, Executive, 0, 0, 0i64);
    Status = IoStatusBlock.Status;
  }
  if ( !Status )
    a2->IoStatus.Information = CurrentStackLocation[1].LowPart << 9;
LABEL_16:
  a2->IoStatus.Status = Status;
  IofCompleteRequest(a2, 0);
  return Status;
}

//----- (0000000000011828) ----------------------------------------------------
__int64 __fastcall sub_11828(PDRIVER_OBJECT DriverObject)
{
  NTSTATUS Device; // edi

  RtlInitUnicodeString(&DeviceName, L"\\Device\\EPMNTDRV");
  RtlInitUnicodeString(&SymbolicLinkName, L"\\DosDevices\\EPMNTDRV");
  Device = IoCreateDevice(DriverObject, 0, &DeviceName, 0x22u, 0, 0, &DeviceObject);
  if ( Device >= 0 )
  {
    Device = IoCreateSymbolicLink(&SymbolicLinkName, &DeviceName);
    if ( Device >= 0 )
    {
      DeviceObject->Flags |= 0x10u;
      DriverObject->MajorFunction[0] = (PDRIVER_DISPATCH)sub_1108C;
      DriverObject->MajorFunction[2] = (PDRIVER_DISPATCH)sub_112F4;
      DriverObject->MajorFunction[14] = (PDRIVER_DISPATCH)sub_11400;
      DriverObject->MajorFunction[18] = (PDRIVER_DISPATCH)sub_11538;
      DriverObject->MajorFunction[3] = (PDRIVER_DISPATCH)sub_116C4;
      DriverObject->MajorFunction[4] = (PDRIVER_DISPATCH)sub_11560;
      DriverObject->DriverUnload = (PDRIVER_UNLOAD)sub_11060;
    }
    else
    {
      IoDeleteDevice(DeviceObject);
    }
  }
  return (unsigned int)Device;
}

//----- (0000000000011950) ----------------------------------------------------
void __fastcall sub_11950(uintptr_t a1)
{
  __int64 v1; // rcx

  if ( a1 != BugCheckParameter2 )
LABEL_4:
    _report_gsfailure(a1);
  v1 = __ROL8__(a1, 16);
  if ( (_WORD)v1 )
  {
    a1 = __ROR8__(v1, 16);
    goto LABEL_4;
  }
}

//----- (0000000000011A70) ----------------------------------------------------
NTSTATUS __fastcall sub_11A70(const wchar_t *a1, size_t a2, size_t *a3, size_t a4)
{
  NTSTATUS result; // eax

  result = 0;
  if ( !a2 || a2 > a4 )
    result = -1073741811;
  if ( a3 )
  {
    if ( result < 0 )
      *a3 = 0i64;
    else
      return RtlStringLengthWorkerW(a1, a2, a3);
  }
  return result;
}

//----- (0000000000016008) ----------------------------------------------------
NTSTATUS __stdcall DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath)
{
  unsigned __int64 v2; // rax

  v2 = BugCheckParameter2;
  if ( !BugCheckParameter2 || BugCheckParameter2 == 0x2B992DDFA232i64 )
  {
    v2 = ((unsigned __int64)&BugCheckParameter2 ^ MEMORY[0xFFFFF78000000320]) & 0xFFFFFFFFFFFFi64;
    if ( !v2 )
      v2 = 0x2B992DDFA232i64;
    BugCheckParameter2 = v2;
  }
  BugCheckParameter3 = ~v2;
  return sub_11828(DriverObject);
}

// nfuncs=34 queued=13 decompiled=13 lumina nreq=0 worse=0 better=0
// ALL OK, 13 function(s) have been successfully decompiled
